// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server2client.proto

#ifndef PROTOBUF_INCLUDED_server2client_2eproto
#define PROTOBUF_INCLUDED_server2client_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_server2client_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_server2client_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_server2client_2eproto();
class server2client;
class server2clientDefaultTypeInternal;
extern server2clientDefaultTypeInternal _server2client_default_instance_;
namespace google {
namespace protobuf {
template<> ::server2client* Arena::CreateMaybeMessage<::server2client>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class server2client final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:server2client) */ {
 public:
  server2client();
  virtual ~server2client();

  server2client(const server2client& from);

  inline server2client& operator=(const server2client& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  server2client(server2client&& from) noexcept
    : server2client() {
    *this = ::std::move(from);
  }

  inline server2client& operator=(server2client&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const server2client& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const server2client* internal_default_instance() {
    return reinterpret_cast<const server2client*>(
               &_server2client_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(server2client* other);
  friend void swap(server2client& a, server2client& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline server2client* New() const final {
    return CreateMaybeMessage<server2client>(nullptr);
  }

  server2client* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<server2client>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const server2client& from);
  void MergeFrom(const server2client& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(server2client* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string command_type = 2;
  bool has_command_type() const;
  void clear_command_type();
  static const int kCommandTypeFieldNumber = 2;
  const ::std::string& command_type() const;
  void set_command_type(const ::std::string& value);
  #if LANG_CXX11
  void set_command_type(::std::string&& value);
  #endif
  void set_command_type(const char* value);
  void set_command_type(const char* value, size_t size);
  ::std::string* mutable_command_type();
  ::std::string* release_command_type();
  void set_allocated_command_type(::std::string* command_type);

  // required int32 type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:server2client)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr command_type_;
  ::google::protobuf::int32 type_;
  friend struct ::TableStruct_server2client_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// server2client

// required int32 type = 1;
inline bool server2client::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void server2client::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 server2client::type() const {
  // @@protoc_insertion_point(field_get:server2client.type)
  return type_;
}
inline void server2client::set_type(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  type_ = value;
  // @@protoc_insertion_point(field_set:server2client.type)
}

// required string command_type = 2;
inline bool server2client::has_command_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void server2client::clear_command_type() {
  command_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& server2client::command_type() const {
  // @@protoc_insertion_point(field_get:server2client.command_type)
  return command_type_.GetNoArena();
}
inline void server2client::set_command_type(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  command_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:server2client.command_type)
}
#if LANG_CXX11
inline void server2client::set_command_type(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  command_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:server2client.command_type)
}
#endif
inline void server2client::set_command_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  command_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:server2client.command_type)
}
inline void server2client::set_command_type(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  command_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:server2client.command_type)
}
inline ::std::string* server2client::mutable_command_type() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:server2client.command_type)
  return command_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* server2client::release_command_type() {
  // @@protoc_insertion_point(field_release:server2client.command_type)
  if (!has_command_type()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return command_type_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void server2client::set_allocated_command_type(::std::string* command_type) {
  if (command_type != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  command_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), command_type);
  // @@protoc_insertion_point(field_set_allocated:server2client.command_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_server2client_2eproto
